### ISSUE TITLE
How to valorize calendar appointment through one variable.

### ISSUE THREAD

**Issue by JackIlPAZZO** [mherrmann/fullcalendar-columns#6] opened 2015-10-20 16:23 UTC
The title isn't clear and this is also not a bug of your code. I need help to understand how I can implement this code:
[code]
$('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'multiColAgendaDay,multiColAgendaWeek'
            },
            views: {
                multiColAgendaDay: {
                    type: 'multiColAgenda',
                    duration: { days: 1 },
                    columns: [
                        { id: 1, name: 'First Column' },
                        { id: 2, name: 'Second Column' }
                    ]
                },
                multiColAgendaWeek: {
                    type: 'multiColAgenda',
                    duration: { weeks: 1 },
                    columns: [
                        { id: 1, name: 'First Column' },
                        { id: 2, name: 'Second Column' }
                    ]
                }
            },
            allDaySlot: false,
            //weekends: false,
            defaultView: 'multiColAgendaWeek',
            defaultDate: '2015-02-12',
            editable: true,
            events: [
                {
                    title: 'Meeting 1',
                    start: '2015-02-12T10:30:00',
                    end: '2015-02-12T12:30:00',
                    column: 0
                },
                {
                    title: 'Meeting 2',
                    start: '2015-02-12T10:30:00',
                    end: '2015-02-12T12:30:00',
                    column: 1
                }
            ]
        });
[/code]

provided in the demo, in my code:

[code]
$.each(response, function(index, rsp) 
            {
                  $.each(rsp.appointments, function(index, appointment)
                  {
                      var event = 
                      {
                           'id': appointment['id'],
                           'title': appointment['service']['name'] + ' - ' 
                                  + appointment['customer']['first_name'] + ' ' 
                                 + appointment['customer']['last_name'],
                           'start': appointment['start_datetime'],
                           'end': appointment['end_datetime'],
                           'allDay': false,
                           'color': '#' +  appointment['res_id']['hex_color'],
                           'data': appointment  
                      };
                      calendarEvents.push(event);
                  })
            });
$calendar.fullCalendar('removeEvents');
$calendar.fullCalendar('addEventSource', calendarEvents);
[/code]

How you can see I'm using the variable event for insert the event in the calendar, but this variable doesn't add the layout of fullcalendar-columns, how I can achieve this result passing all into one variable? Someone could help me out?

**Comment by mherrmann** [comment] 2015-10-20 16:26
Sorry, I don't have time to help you at the moment. I would suggest you ask the question on StackOverflow. As you said yourself - this is not a bug of the existing code, nor a feature request. I'm therefore closing this issue.

**Closed as completed by mherrmann** 2015-10-20 16:26 UTC

**Comment by JackIlPAZZO** [comment] 2015-10-20 16:37
I know this isn't a bug but I need help, if you close this thread anyone could help me..

**Comment by mherrmann** [comment] 2015-10-20 16:38
Ask on StackOverflow!
